### ISSUE TITLE
'&' !== ("")["link"](0+")[10]

### ISSUE THREAD

**Issue by jserNc** [aemkei/jsfuck#63]
Expression ("")["link"](0+")[10] error : Uncaught SyntaxError: Invalid or unexpected token

**Comment by aemkei** [comment]
Looks like it was introduced here:

https://github.com/aemkei/jsfuck/commit/b618bf470c21ed3f76dc267c1feefe7e4d684490

cc @subzey

**Comment by hazzik** [comment]
@aemkei, @jserNc.  What are the evidences of that `'&' !== ("")["link"](0+")[10]`? Which browser? 

The repository has tests, and according to these tests all ASCII7 characters are generated correctly and produce correct results.

Because of the peculiarity of how the substitutions work in the JSFuck the `"` symbol if needed to be substituted by the code should not be enclosed into the quotes (`'"'`) or escaped (`\"`). The original expression for `&` is `("")["link"](0+'"')[10]` (note the difference between what's in the code and here: the `"` is not escaped.

**Comment by aemkei** [comment]
You are right. Thanks for the clarification!
